version: "3"

services:
  strapi_b_web:
    image: registry.cn-zhangjiakou.aliyuncs.com/rv/strapi_matrix:blog-web
    # image: registry-vpc.cn-zhangjiakou.aliyuncs.com/rv/strapi_matrix:blog-web
    volumes:
      - .:/wrap/app
    labels:
      - "traefik.http.routers.strapi_b_web.rule=Host(`localhost`)"
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  default:
    external:
      name: lary
